version: "3.10"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastchat:latest
    ports:
      - "8501:8501"
    volumes:
     - ${DOCKER_VOLUME_DIRECTORY:-.}:/app
    working_dir: /app
    entrypoint: 
      - uvicorn
      - main:app
      - --host
      - 0.0.0.0
      - --port
      - '8501'
