target("demo", {kind = "binary", files = "demo.c"})
target("tcp_s", {kind = "binary", files = "tcp_s.c"})
target("tcp_c", {kind = "binary", files = "tcp_c.c"})
target("udp_s", {kind = "binary", files = "udp_s.c"})
target("udp_c", {kind = "binary", files = "udp_c.c"})
